// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<ConsoleWrite>", Scope = "member", Target = "~M:Embassy.Program.Program.MainMenu~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<ConsoleWrite>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantMenu")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<ConsoleWrite>", Scope = "member", Target = "~M:Embassy.Program.Program.AgencyMenu")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<ConsoleWrite>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentMenu")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<database>", Scope = "member", Target = "~M:Embassy.Program.Program.Main")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Readline>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantMenu")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<DatabaseConnected>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantMenu")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1121:Use built-in type alias", Justification = "<String>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantMenu")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Consolewrite>", Scope = "member", Target = "~M:Embassy.Program.Program.VisaMenu")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<ConsoleReadline>", Scope = "member", Target = "~M:Embassy.Program.Program.VisaMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.VisaMenu")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<emb>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentMenu")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Readline>", Scope = "member", Target = "~M:Embassy.Program.Program.AgencyMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.AgencyMenu")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<ConsoleReadline>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentMenu")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<ConsoleWriteLine>", Scope = "member", Target = "~M:Embassy.Program.Program.GeneralMenu~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<cw>", Scope = "member", Target = "~M:Embassy.Program.Program.VisaBusinessLogicMenu")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<intparse>", Scope = "member", Target = "~M:Embassy.Program.Program.VisaBusinessLogicMenu")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<console>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentBusinessLogicMenu")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<readline>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentBusinessLogicMenu")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<console>", Scope = "member", Target = "~M:Embassy.Program.Program.AgencyBusinessLogicMenu")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<intparse>", Scope = "member", Target = "~M:Embassy.Program.Program.AgencyBusinessLogicMenu")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<consoleWrite>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantBusinessLogicMenu")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<parse>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantBusinessLogicMenu")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<contextDb>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentBusinessLogicMenu")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Contextdb>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantBusinessLogicMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.AgencyBusinessLogicMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.ApplicantBusinessLogicMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.PaymentBusinessLogicMenu")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<catch>", Scope = "member", Target = "~M:Embassy.Program.Program.VisaBusinessLogicMenu")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<embctx>", Scope = "member", Target = "~M:Embassy.Program.Program.VisaBusinessLogicMenu")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<emb>", Scope = "member", Target = "~M:Embassy.Program.Program.AgencyBusinessLogicMenu")]
